---
- name: OpenStack end to end configuration
  hosts: control_node
  gather_facts: False
  collections:
    - tok.openstack

  tasks:  
    - name: Setup control node
      import_role: 
        name: openstack_control_node_setup  

...

